### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by Dani-Gordon2** [Dani-Gordon/github-refresher#1]
I think it looks better if the main title is a bit more turquoise in color

```css
h1 {
  color: #37d5c5;
}
```
